# Generated by Django 3.2.7 on 2021-09-11 14:54
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='arch_console_organization',
        ),
        migrations.AlterModelTable(
            name='organizationmember',
            table='arch_console_organization_member',
        ),
        migrations.AlterModelTable(
            name='organizationowner',
            table='arch_console_organization_owner',
        ),
        migrations.AlterModelTable(
            name='team',
            table='arch_console_team',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='arch_console_team_member',
        ),
        migrations.AlterModelTable(
            name='teamowner',
            table='arch_console_team_owner',
        ),
    ]
