# Generated by Django 3.2.7 on 2021-09-21 17:05
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20210911_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='date_added',
            new_name='date_invited',
        ),
        migrations.RenameField(
            model_name='teamowner',
            old_name='date_added',
            new_name='date_invited',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='invite_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationowner',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationowner',
            name='invite_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organizationowner',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='invite_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='teamowner',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamowner',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamowner',
            name='invite_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='teamowner',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20),
        ),
    ]
