# Generated by Django 3.2.7 on 2021-09-23 18:47
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20210921_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invite_type', models.CharField(choices=[('ORG_OWNER', 'Organization Owner'), ('ORG_MEMBER', 'Organization Member')], max_length=20)),
                ('invited_date', models.DateTimeField()),
                ('invite_accepted_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'arch_console_email_invite',
            },
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='date_invited',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='invite_accepted',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='organizationowner',
            name='date_invited',
        ),
        migrations.RemoveField(
            model_name='organizationowner',
            name='invite_accepted',
        ),
        migrations.RemoveField(
            model_name='organizationowner',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='date_invited',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='invite_accepted',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='teamowner',
            name='date_invited',
        ),
        migrations.RemoveField(
            model_name='teamowner',
            name='invite_accepted',
        ),
        migrations.RemoveField(
            model_name='teamowner',
            name='invite_code',
        ),
    ]
