# Generated by Django 3.2.7 on 2021-09-23 18:57
# pylint: skip-file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_auto_20210924_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invite_type', models.CharField(choices=[('ORG_OWNER', 'Organization Owner'), ('ORG_MEMBER', 'Organization Member')], max_length=20)),
                ('invited_date', models.DateTimeField()),
                ('invite_accepted_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.organization')),
            ],
            options={
                'db_table': 'arch_console_organization_invite',
            },
        ),
        migrations.DeleteModel(
            name='EmailInvite',
        ),
    ]
