# Generated by Django 3.2.7 on 2021-09-23 19:08
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_auto_20210924_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationinvite',
            old_name='invite_accepted_date',
            new_name='invite_accepted_date_time',
        ),
        migrations.RenameField(
            model_name='organizationinvite',
            old_name='invited_date',
            new_name='invited_date_time',
        ),
    ]
