# Generated by Django 3.2.7 on 2021-09-23 19:19
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_auto_20210924_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvite',
            name='invite_accepted_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='invited_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
