# Generated by Django 3.2.7 on 2021-09-11 14:00
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='arch_core_user_profile',
        ),
    ]
