# Generated by Django 3.2.7 on 2021-09-11 14:18
# pylint: skip-file
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Employee',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='arch_core_employee',
        ),
    ]
