# Generated by Django 3.2.7 on 2021-10-04 19:32
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduledemail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scheduledemail',
            table='arch_core_scheduled_email',
        ),
    ]
